# image will be published to ghcr.io/<user>/<name>
name: jackm97-bazzite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination:
          / # copies files/system/* (* means everything inside it) into your image's root folder /
          # put configuration files you want in /usr/etc/ inside the image
          # while putting files in /etc/ is done on booted system by system administrators.
          # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      - https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
      - insync.repo
    keys:
      - https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
    install:
      - PackageKit
      - gnome-software-rpm-ostree
      - kitty
      - nvidia-container-toolkit
      - insync
      # - insync-nautilus.rpm
      - gcc
      - gcc-c++
    remove:

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
        # only normal flatpak applications are (like Floorp Lightning web browser in this example).
        # Installing different branches of the same Flatpak is not supported.
        - com.microsoft.Edge
        - com.mattjakeman.ExtensionManager
        - com.spotify.Client
        - md.obsidian.Obsidian
        - org.onlyoffice.desktopeditors
        - org.audacityteam.Audacity
        - com.github.tchx84.Flatseal
        - org.paraview.ParaView
        - com.obsproject.Studio
        - org.gimp.GIMP
        - org.darktable.Darktable
      remove:

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
